%% Product Guide
% This page is generated by HDL Coder for IP core:
% lms_filter_ipcore.
% 
% Please open the IP Core Generation Report using following link:
% 
% <file://lms_ip_core_report.html doc/lms_ip_core_report.html>
