-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\lms\LMS_pkg.vhd
-- Created: 2018-04-02 19:23:30
-- 
-- Generated by MATLAB 8.5 and HDL Coder 3.6
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE LMS_pkg IS
  TYPE vector_of_signed24 IS ARRAY (NATURAL RANGE <>) OF signed(23 DOWNTO 0);
END LMS_pkg;

