-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\lms\LMS.vhd
-- Created: 2018-03-30 20:04:39
-- 
-- Generated by MATLAB 8.5 and HDL Coder 3.6
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 2.26757e-05
-- Target subsystem base rate: 2.26757e-05
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        2.26757e-05
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- e_k                           ce_out        2.26757e-05
-- o_k                           ce_out        2.26757e-05
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: LMS
-- Source Path: lms/LMS
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.LMS_pkg.ALL;

ENTITY LMS_Filter IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        x_k                               :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En23
        d_k                               :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En23
        ce_out                            :   OUT   std_logic;
        e_k                               :   OUT   std_logic_vector(23 DOWNTO 0);  -- sfix24_En23
        o_k                               :   OUT   std_logic_vector(23 DOWNTO 0)  -- sfix24_En23
        );
END LMS_Filter;


ARCHITECTURE rtl OF LMS_Filter IS

  -- Constants
  CONSTANT C_LMS_FILTER_STEP_SIZE         : signed(23 DOWNTO 0) := "011001100110011001100110";  -- sfix24_En26

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL x_k_signed                       : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL d_k_signed                       : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL LMS_Filter_out1                  : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL LMS_Filter_out2                  : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL weight                           : vector_of_signed24(0 TO 15);  -- sfix24_En23 [16]
  SIGNAL filter_sum                       : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL data_pipeline                    : vector_of_signed24(0 TO 15);  -- sfix24_En23 [16]
  SIGNAL data_pipeline_tmp                : vector_of_signed24(0 TO 14);  -- sfix24_En23 [15]
  SIGNAL filter_products                  : vector_of_signed24(0 TO 15);  -- sfix24_En23 [16]
  SIGNAL mul_temp                         : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_1                       : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_2                       : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_3                       : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_4                       : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_5                       : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_6                       : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_7                       : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_8                       : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_9                       : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_10                      : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_11                      : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_12                      : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_13                      : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_14                      : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_15                      : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL sum_1                            : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast                         : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_1                       : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp                         : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL sum_2                            : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_2                       : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_3                       : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_1                       : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL sum_3                            : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_4                       : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_5                       : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_2                       : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL sum_4                            : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_6                       : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_7                       : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_3                       : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL sum_5                            : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_8                       : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_9                       : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_4                       : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL sum_6                            : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_10                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_11                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_5                       : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL sum_7                            : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_12                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_13                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_6                       : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL sum_8                            : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_14                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_15                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_7                       : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL sum_9                            : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_16                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_17                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_8                       : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL sum_10                           : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_18                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_19                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_9                       : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL sum_11                           : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_20                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_21                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_10                      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL sum_12                           : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_22                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_23                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_11                      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL sum_13                           : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_24                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_25                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_12                      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL sum_14                           : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_26                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_27                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_13                      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL add_cast_28                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_29                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_14                      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL sub_cast                         : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL sub_cast_1                       : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL sub_temp                         : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL mu_err                           : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL mul_temp_16                      : signed(47 DOWNTO 0);  -- sfix48_En49
  SIGNAL mu_err_data_prod                 : vector_of_signed24(0 TO 15);  -- sfix24_En23 [16]
  SIGNAL mul_temp_17                      : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_18                      : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_19                      : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_20                      : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_21                      : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_22                      : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_23                      : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_24                      : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_25                      : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_26                      : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_27                      : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_28                      : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_29                      : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_30                      : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_31                      : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL mul_temp_32                      : signed(47 DOWNTO 0);  -- sfix48_En46
  SIGNAL weight_adder_output              : vector_of_signed24(0 TO 15);  -- sfix24_En23 [16]
  SIGNAL add_cast_30                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_31                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_15                      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL add_cast_32                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_33                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_16                      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL add_cast_34                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_35                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_17                      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL add_cast_36                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_37                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_18                      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL add_cast_38                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_39                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_19                      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL add_cast_40                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_41                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_20                      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL add_cast_42                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_43                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_21                      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL add_cast_44                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_45                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_22                      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL add_cast_46                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_47                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_23                      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL add_cast_48                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_49                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_24                      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL add_cast_50                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_51                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_25                      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL add_cast_52                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_53                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_26                      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL add_cast_54                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_55                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_27                      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL add_cast_56                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_57                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_28                      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL add_cast_58                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_59                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_29                      : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL add_cast_60                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_cast_61                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL add_temp_30                      : signed(24 DOWNTO 0);  -- sfix25_En23

BEGIN
  x_k_signed <= signed(x_k);

  d_k_signed <= signed(d_k);

  enb <= clk_enable;


-- ***********************
-- ********* LMS *********
-- ***********************

-- * LMS: FIR section

  LMS_Filter_del_temp_process1 : PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF reset = '0' THEN
        data_pipeline_tmp <= (OTHERS => (OTHERS => '0'));
      ELSIF enb = '1' THEN
        data_pipeline_tmp(0 TO 13) <= data_pipeline_tmp(1 TO 14);
        data_pipeline_tmp(14) <= x_k_signed;
      END IF;
    END IF;
  END PROCESS LMS_Filter_del_temp_process1;

  data_pipeline(0 TO 14) <= data_pipeline_tmp(0 TO 14);
  data_pipeline(15) <= x_k_signed;

  mul_temp <= data_pipeline(0) * weight(0);
  filter_products(0) <= resize(shift_right(mul_temp(46 DOWNTO 0) + ( "0" & (mul_temp(23) & NOT mul_temp(23) & NOT mul_temp(23) & NOT mul_temp(23) & NOT mul_temp(23) & NOT mul_temp(23) & NOT mul_temp(23) & NOT mul_temp(23) & NOT mul_temp(23) & NOT mul_temp(23) & NOT mul_temp(23) & NOT mul_temp(23) & NOT mul_temp(23) & NOT mul_temp(23) & NOT mul_temp(23) & NOT mul_temp(23) & NOT mul_temp(23) & NOT mul_temp(23) & NOT mul_temp(23) & NOT mul_temp(23) & NOT mul_temp(23) & NOT mul_temp(23) & NOT mul_temp(23))), 23), 24);

  mul_temp_1 <= data_pipeline(1) * weight(1);
  filter_products(1) <= resize(shift_right(mul_temp_1(46 DOWNTO 0) + ( "0" & (mul_temp_1(23) & NOT mul_temp_1(23) & NOT mul_temp_1(23) & NOT mul_temp_1(23) & NOT mul_temp_1(23) & NOT mul_temp_1(23) & NOT mul_temp_1(23) & NOT mul_temp_1(23) & NOT mul_temp_1(23) & NOT mul_temp_1(23) & NOT mul_temp_1(23) & NOT mul_temp_1(23) & NOT mul_temp_1(23) & NOT mul_temp_1(23) & NOT mul_temp_1(23) & NOT mul_temp_1(23) & NOT mul_temp_1(23) & NOT mul_temp_1(23) & NOT mul_temp_1(23) & NOT mul_temp_1(23) & NOT mul_temp_1(23) & NOT mul_temp_1(23) & NOT mul_temp_1(23))), 23), 24);

  mul_temp_2 <= data_pipeline(2) * weight(2);
  filter_products(2) <= resize(shift_right(mul_temp_2(46 DOWNTO 0) + ( "0" & (mul_temp_2(23) & NOT mul_temp_2(23) & NOT mul_temp_2(23) & NOT mul_temp_2(23) & NOT mul_temp_2(23) & NOT mul_temp_2(23) & NOT mul_temp_2(23) & NOT mul_temp_2(23) & NOT mul_temp_2(23) & NOT mul_temp_2(23) & NOT mul_temp_2(23) & NOT mul_temp_2(23) & NOT mul_temp_2(23) & NOT mul_temp_2(23) & NOT mul_temp_2(23) & NOT mul_temp_2(23) & NOT mul_temp_2(23) & NOT mul_temp_2(23) & NOT mul_temp_2(23) & NOT mul_temp_2(23) & NOT mul_temp_2(23) & NOT mul_temp_2(23) & NOT mul_temp_2(23))), 23), 24);

  mul_temp_3 <= data_pipeline(3) * weight(3);
  filter_products(3) <= resize(shift_right(mul_temp_3(46 DOWNTO 0) + ( "0" & (mul_temp_3(23) & NOT mul_temp_3(23) & NOT mul_temp_3(23) & NOT mul_temp_3(23) & NOT mul_temp_3(23) & NOT mul_temp_3(23) & NOT mul_temp_3(23) & NOT mul_temp_3(23) & NOT mul_temp_3(23) & NOT mul_temp_3(23) & NOT mul_temp_3(23) & NOT mul_temp_3(23) & NOT mul_temp_3(23) & NOT mul_temp_3(23) & NOT mul_temp_3(23) & NOT mul_temp_3(23) & NOT mul_temp_3(23) & NOT mul_temp_3(23) & NOT mul_temp_3(23) & NOT mul_temp_3(23) & NOT mul_temp_3(23) & NOT mul_temp_3(23) & NOT mul_temp_3(23))), 23), 24);

  mul_temp_4 <= data_pipeline(4) * weight(4);
  filter_products(4) <= resize(shift_right(mul_temp_4(46 DOWNTO 0) + ( "0" & (mul_temp_4(23) & NOT mul_temp_4(23) & NOT mul_temp_4(23) & NOT mul_temp_4(23) & NOT mul_temp_4(23) & NOT mul_temp_4(23) & NOT mul_temp_4(23) & NOT mul_temp_4(23) & NOT mul_temp_4(23) & NOT mul_temp_4(23) & NOT mul_temp_4(23) & NOT mul_temp_4(23) & NOT mul_temp_4(23) & NOT mul_temp_4(23) & NOT mul_temp_4(23) & NOT mul_temp_4(23) & NOT mul_temp_4(23) & NOT mul_temp_4(23) & NOT mul_temp_4(23) & NOT mul_temp_4(23) & NOT mul_temp_4(23) & NOT mul_temp_4(23) & NOT mul_temp_4(23))), 23), 24);

  mul_temp_5 <= data_pipeline(5) * weight(5);
  filter_products(5) <= resize(shift_right(mul_temp_5(46 DOWNTO 0) + ( "0" & (mul_temp_5(23) & NOT mul_temp_5(23) & NOT mul_temp_5(23) & NOT mul_temp_5(23) & NOT mul_temp_5(23) & NOT mul_temp_5(23) & NOT mul_temp_5(23) & NOT mul_temp_5(23) & NOT mul_temp_5(23) & NOT mul_temp_5(23) & NOT mul_temp_5(23) & NOT mul_temp_5(23) & NOT mul_temp_5(23) & NOT mul_temp_5(23) & NOT mul_temp_5(23) & NOT mul_temp_5(23) & NOT mul_temp_5(23) & NOT mul_temp_5(23) & NOT mul_temp_5(23) & NOT mul_temp_5(23) & NOT mul_temp_5(23) & NOT mul_temp_5(23) & NOT mul_temp_5(23))), 23), 24);

  mul_temp_6 <= data_pipeline(6) * weight(6);
  filter_products(6) <= resize(shift_right(mul_temp_6(46 DOWNTO 0) + ( "0" & (mul_temp_6(23) & NOT mul_temp_6(23) & NOT mul_temp_6(23) & NOT mul_temp_6(23) & NOT mul_temp_6(23) & NOT mul_temp_6(23) & NOT mul_temp_6(23) & NOT mul_temp_6(23) & NOT mul_temp_6(23) & NOT mul_temp_6(23) & NOT mul_temp_6(23) & NOT mul_temp_6(23) & NOT mul_temp_6(23) & NOT mul_temp_6(23) & NOT mul_temp_6(23) & NOT mul_temp_6(23) & NOT mul_temp_6(23) & NOT mul_temp_6(23) & NOT mul_temp_6(23) & NOT mul_temp_6(23) & NOT mul_temp_6(23) & NOT mul_temp_6(23) & NOT mul_temp_6(23))), 23), 24);

  mul_temp_7 <= data_pipeline(7) * weight(7);
  filter_products(7) <= resize(shift_right(mul_temp_7(46 DOWNTO 0) + ( "0" & (mul_temp_7(23) & NOT mul_temp_7(23) & NOT mul_temp_7(23) & NOT mul_temp_7(23) & NOT mul_temp_7(23) & NOT mul_temp_7(23) & NOT mul_temp_7(23) & NOT mul_temp_7(23) & NOT mul_temp_7(23) & NOT mul_temp_7(23) & NOT mul_temp_7(23) & NOT mul_temp_7(23) & NOT mul_temp_7(23) & NOT mul_temp_7(23) & NOT mul_temp_7(23) & NOT mul_temp_7(23) & NOT mul_temp_7(23) & NOT mul_temp_7(23) & NOT mul_temp_7(23) & NOT mul_temp_7(23) & NOT mul_temp_7(23) & NOT mul_temp_7(23) & NOT mul_temp_7(23))), 23), 24);

  mul_temp_8 <= data_pipeline(8) * weight(8);
  filter_products(8) <= resize(shift_right(mul_temp_8(46 DOWNTO 0) + ( "0" & (mul_temp_8(23) & NOT mul_temp_8(23) & NOT mul_temp_8(23) & NOT mul_temp_8(23) & NOT mul_temp_8(23) & NOT mul_temp_8(23) & NOT mul_temp_8(23) & NOT mul_temp_8(23) & NOT mul_temp_8(23) & NOT mul_temp_8(23) & NOT mul_temp_8(23) & NOT mul_temp_8(23) & NOT mul_temp_8(23) & NOT mul_temp_8(23) & NOT mul_temp_8(23) & NOT mul_temp_8(23) & NOT mul_temp_8(23) & NOT mul_temp_8(23) & NOT mul_temp_8(23) & NOT mul_temp_8(23) & NOT mul_temp_8(23) & NOT mul_temp_8(23) & NOT mul_temp_8(23))), 23), 24);

  mul_temp_9 <= data_pipeline(9) * weight(9);
  filter_products(9) <= resize(shift_right(mul_temp_9(46 DOWNTO 0) + ( "0" & (mul_temp_9(23) & NOT mul_temp_9(23) & NOT mul_temp_9(23) & NOT mul_temp_9(23) & NOT mul_temp_9(23) & NOT mul_temp_9(23) & NOT mul_temp_9(23) & NOT mul_temp_9(23) & NOT mul_temp_9(23) & NOT mul_temp_9(23) & NOT mul_temp_9(23) & NOT mul_temp_9(23) & NOT mul_temp_9(23) & NOT mul_temp_9(23) & NOT mul_temp_9(23) & NOT mul_temp_9(23) & NOT mul_temp_9(23) & NOT mul_temp_9(23) & NOT mul_temp_9(23) & NOT mul_temp_9(23) & NOT mul_temp_9(23) & NOT mul_temp_9(23) & NOT mul_temp_9(23))), 23), 24);

  mul_temp_10 <= data_pipeline(10) * weight(10);
  filter_products(10) <= resize(shift_right(mul_temp_10(46 DOWNTO 0) + ( "0" & (mul_temp_10(23) & NOT mul_temp_10(23) & NOT mul_temp_10(23) & NOT mul_temp_10(23) & NOT mul_temp_10(23) & NOT mul_temp_10(23) & NOT mul_temp_10(23) & NOT mul_temp_10(23) & NOT mul_temp_10(23) & NOT mul_temp_10(23) & NOT mul_temp_10(23) & NOT mul_temp_10(23) & NOT mul_temp_10(23) & NOT mul_temp_10(23) & NOT mul_temp_10(23) & NOT mul_temp_10(23) & NOT mul_temp_10(23) & NOT mul_temp_10(23) & NOT mul_temp_10(23) & NOT mul_temp_10(23) & NOT mul_temp_10(23) & NOT mul_temp_10(23) & NOT mul_temp_10(23))), 23), 24);

  mul_temp_11 <= data_pipeline(11) * weight(11);
  filter_products(11) <= resize(shift_right(mul_temp_11(46 DOWNTO 0) + ( "0" & (mul_temp_11(23) & NOT mul_temp_11(23) & NOT mul_temp_11(23) & NOT mul_temp_11(23) & NOT mul_temp_11(23) & NOT mul_temp_11(23) & NOT mul_temp_11(23) & NOT mul_temp_11(23) & NOT mul_temp_11(23) & NOT mul_temp_11(23) & NOT mul_temp_11(23) & NOT mul_temp_11(23) & NOT mul_temp_11(23) & NOT mul_temp_11(23) & NOT mul_temp_11(23) & NOT mul_temp_11(23) & NOT mul_temp_11(23) & NOT mul_temp_11(23) & NOT mul_temp_11(23) & NOT mul_temp_11(23) & NOT mul_temp_11(23) & NOT mul_temp_11(23) & NOT mul_temp_11(23))), 23), 24);

  mul_temp_12 <= data_pipeline(12) * weight(12);
  filter_products(12) <= resize(shift_right(mul_temp_12(46 DOWNTO 0) + ( "0" & (mul_temp_12(23) & NOT mul_temp_12(23) & NOT mul_temp_12(23) & NOT mul_temp_12(23) & NOT mul_temp_12(23) & NOT mul_temp_12(23) & NOT mul_temp_12(23) & NOT mul_temp_12(23) & NOT mul_temp_12(23) & NOT mul_temp_12(23) & NOT mul_temp_12(23) & NOT mul_temp_12(23) & NOT mul_temp_12(23) & NOT mul_temp_12(23) & NOT mul_temp_12(23) & NOT mul_temp_12(23) & NOT mul_temp_12(23) & NOT mul_temp_12(23) & NOT mul_temp_12(23) & NOT mul_temp_12(23) & NOT mul_temp_12(23) & NOT mul_temp_12(23) & NOT mul_temp_12(23))), 23), 24);

  mul_temp_13 <= data_pipeline(13) * weight(13);
  filter_products(13) <= resize(shift_right(mul_temp_13(46 DOWNTO 0) + ( "0" & (mul_temp_13(23) & NOT mul_temp_13(23) & NOT mul_temp_13(23) & NOT mul_temp_13(23) & NOT mul_temp_13(23) & NOT mul_temp_13(23) & NOT mul_temp_13(23) & NOT mul_temp_13(23) & NOT mul_temp_13(23) & NOT mul_temp_13(23) & NOT mul_temp_13(23) & NOT mul_temp_13(23) & NOT mul_temp_13(23) & NOT mul_temp_13(23) & NOT mul_temp_13(23) & NOT mul_temp_13(23) & NOT mul_temp_13(23) & NOT mul_temp_13(23) & NOT mul_temp_13(23) & NOT mul_temp_13(23) & NOT mul_temp_13(23) & NOT mul_temp_13(23) & NOT mul_temp_13(23))), 23), 24);

  mul_temp_14 <= data_pipeline(14) * weight(14);
  filter_products(14) <= resize(shift_right(mul_temp_14(46 DOWNTO 0) + ( "0" & (mul_temp_14(23) & NOT mul_temp_14(23) & NOT mul_temp_14(23) & NOT mul_temp_14(23) & NOT mul_temp_14(23) & NOT mul_temp_14(23) & NOT mul_temp_14(23) & NOT mul_temp_14(23) & NOT mul_temp_14(23) & NOT mul_temp_14(23) & NOT mul_temp_14(23) & NOT mul_temp_14(23) & NOT mul_temp_14(23) & NOT mul_temp_14(23) & NOT mul_temp_14(23) & NOT mul_temp_14(23) & NOT mul_temp_14(23) & NOT mul_temp_14(23) & NOT mul_temp_14(23) & NOT mul_temp_14(23) & NOT mul_temp_14(23) & NOT mul_temp_14(23) & NOT mul_temp_14(23))), 23), 24);

  mul_temp_15 <= data_pipeline(15) * weight(15);
  filter_products(15) <= resize(shift_right(mul_temp_15(46 DOWNTO 0) + ( "0" & (mul_temp_15(23) & NOT mul_temp_15(23) & NOT mul_temp_15(23) & NOT mul_temp_15(23) & NOT mul_temp_15(23) & NOT mul_temp_15(23) & NOT mul_temp_15(23) & NOT mul_temp_15(23) & NOT mul_temp_15(23) & NOT mul_temp_15(23) & NOT mul_temp_15(23) & NOT mul_temp_15(23) & NOT mul_temp_15(23) & NOT mul_temp_15(23) & NOT mul_temp_15(23) & NOT mul_temp_15(23) & NOT mul_temp_15(23) & NOT mul_temp_15(23) & NOT mul_temp_15(23) & NOT mul_temp_15(23) & NOT mul_temp_15(23) & NOT mul_temp_15(23) & NOT mul_temp_15(23))), 23), 24);

-- linear sum of filter products

  add_cast <= filter_products(0);
  add_cast_1 <= filter_products(1);
  add_temp <= resize(add_cast, 25) + resize(add_cast_1, 25);
  sum_1 <= add_temp(23 DOWNTO 0);

  add_cast_2 <= sum_1;
  add_cast_3 <= filter_products(2);
  add_temp_1 <= resize(add_cast_2, 25) + resize(add_cast_3, 25);
  sum_2 <= add_temp_1(23 DOWNTO 0);

  add_cast_4 <= sum_2;
  add_cast_5 <= filter_products(3);
  add_temp_2 <= resize(add_cast_4, 25) + resize(add_cast_5, 25);
  sum_3 <= add_temp_2(23 DOWNTO 0);

  add_cast_6 <= sum_3;
  add_cast_7 <= filter_products(4);
  add_temp_3 <= resize(add_cast_6, 25) + resize(add_cast_7, 25);
  sum_4 <= add_temp_3(23 DOWNTO 0);

  add_cast_8 <= sum_4;
  add_cast_9 <= filter_products(5);
  add_temp_4 <= resize(add_cast_8, 25) + resize(add_cast_9, 25);
  sum_5 <= add_temp_4(23 DOWNTO 0);

  add_cast_10 <= sum_5;
  add_cast_11 <= filter_products(6);
  add_temp_5 <= resize(add_cast_10, 25) + resize(add_cast_11, 25);
  sum_6 <= add_temp_5(23 DOWNTO 0);

  add_cast_12 <= sum_6;
  add_cast_13 <= filter_products(7);
  add_temp_6 <= resize(add_cast_12, 25) + resize(add_cast_13, 25);
  sum_7 <= add_temp_6(23 DOWNTO 0);

  add_cast_14 <= sum_7;
  add_cast_15 <= filter_products(8);
  add_temp_7 <= resize(add_cast_14, 25) + resize(add_cast_15, 25);
  sum_8 <= add_temp_7(23 DOWNTO 0);

  add_cast_16 <= sum_8;
  add_cast_17 <= filter_products(9);
  add_temp_8 <= resize(add_cast_16, 25) + resize(add_cast_17, 25);
  sum_9 <= add_temp_8(23 DOWNTO 0);

  add_cast_18 <= sum_9;
  add_cast_19 <= filter_products(10);
  add_temp_9 <= resize(add_cast_18, 25) + resize(add_cast_19, 25);
  sum_10 <= add_temp_9(23 DOWNTO 0);

  add_cast_20 <= sum_10;
  add_cast_21 <= filter_products(11);
  add_temp_10 <= resize(add_cast_20, 25) + resize(add_cast_21, 25);
  sum_11 <= add_temp_10(23 DOWNTO 0);

  add_cast_22 <= sum_11;
  add_cast_23 <= filter_products(12);
  add_temp_11 <= resize(add_cast_22, 25) + resize(add_cast_23, 25);
  sum_12 <= add_temp_11(23 DOWNTO 0);

  add_cast_24 <= sum_12;
  add_cast_25 <= filter_products(13);
  add_temp_12 <= resize(add_cast_24, 25) + resize(add_cast_25, 25);
  sum_13 <= add_temp_12(23 DOWNTO 0);

  add_cast_26 <= sum_13;
  add_cast_27 <= filter_products(14);
  add_temp_13 <= resize(add_cast_26, 25) + resize(add_cast_27, 25);
  sum_14 <= add_temp_13(23 DOWNTO 0);

  add_cast_28 <= sum_14;
  add_cast_29 <= filter_products(15);
  add_temp_14 <= resize(add_cast_28, 25) + resize(add_cast_29, 25);
  filter_sum <= add_temp_14(23 DOWNTO 0);

  LMS_Filter_out1 <= filter_sum;

-- * Calculate Filter Error

  sub_cast <= d_k_signed;
  sub_cast_1 <= filter_sum;
  sub_temp <= resize(sub_cast, 25) - resize(sub_cast_1, 25);
  LMS_Filter_out2 <= sub_temp(23 DOWNTO 0);

-- ***** LMS Weight Update Function *****

  mul_temp_16 <= C_LMS_FILTER_STEP_SIZE * LMS_Filter_out2;
  mu_err <= resize(shift_right(mul_temp_16(47) & mul_temp_16(47 DOWNTO 0) + ( "0" & (mul_temp_16(26) & NOT mul_temp_16(26) & NOT mul_temp_16(26) & NOT mul_temp_16(26) & NOT mul_temp_16(26) & NOT mul_temp_16(26) & NOT mul_temp_16(26) & NOT mul_temp_16(26) & NOT mul_temp_16(26) & NOT mul_temp_16(26) & NOT mul_temp_16(26) & NOT mul_temp_16(26) & NOT mul_temp_16(26) & NOT mul_temp_16(26) & NOT mul_temp_16(26) & NOT mul_temp_16(26) & NOT mul_temp_16(26) & NOT mul_temp_16(26) & NOT mul_temp_16(26) & NOT mul_temp_16(26) & NOT mul_temp_16(26) & NOT mul_temp_16(26) & NOT mul_temp_16(26) & NOT mul_temp_16(26) & NOT mul_temp_16(26) & NOT mul_temp_16(26))), 26), 24);

  mul_temp_17 <= data_pipeline(0) * mu_err;
  mu_err_data_prod(0) <= resize(shift_right(mul_temp_17(46 DOWNTO 0) + ( "0" & (mul_temp_17(23) & NOT mul_temp_17(23) & NOT mul_temp_17(23) & NOT mul_temp_17(23) & NOT mul_temp_17(23) & NOT mul_temp_17(23) & NOT mul_temp_17(23) & NOT mul_temp_17(23) & NOT mul_temp_17(23) & NOT mul_temp_17(23) & NOT mul_temp_17(23) & NOT mul_temp_17(23) & NOT mul_temp_17(23) & NOT mul_temp_17(23) & NOT mul_temp_17(23) & NOT mul_temp_17(23) & NOT mul_temp_17(23) & NOT mul_temp_17(23) & NOT mul_temp_17(23) & NOT mul_temp_17(23) & NOT mul_temp_17(23) & NOT mul_temp_17(23) & NOT mul_temp_17(23))), 23), 24);

  mul_temp_18 <= data_pipeline(1) * mu_err;
  mu_err_data_prod(1) <= resize(shift_right(mul_temp_18(46 DOWNTO 0) + ( "0" & (mul_temp_18(23) & NOT mul_temp_18(23) & NOT mul_temp_18(23) & NOT mul_temp_18(23) & NOT mul_temp_18(23) & NOT mul_temp_18(23) & NOT mul_temp_18(23) & NOT mul_temp_18(23) & NOT mul_temp_18(23) & NOT mul_temp_18(23) & NOT mul_temp_18(23) & NOT mul_temp_18(23) & NOT mul_temp_18(23) & NOT mul_temp_18(23) & NOT mul_temp_18(23) & NOT mul_temp_18(23) & NOT mul_temp_18(23) & NOT mul_temp_18(23) & NOT mul_temp_18(23) & NOT mul_temp_18(23) & NOT mul_temp_18(23) & NOT mul_temp_18(23) & NOT mul_temp_18(23))), 23), 24);

  mul_temp_19 <= data_pipeline(2) * mu_err;
  mu_err_data_prod(2) <= resize(shift_right(mul_temp_19(46 DOWNTO 0) + ( "0" & (mul_temp_19(23) & NOT mul_temp_19(23) & NOT mul_temp_19(23) & NOT mul_temp_19(23) & NOT mul_temp_19(23) & NOT mul_temp_19(23) & NOT mul_temp_19(23) & NOT mul_temp_19(23) & NOT mul_temp_19(23) & NOT mul_temp_19(23) & NOT mul_temp_19(23) & NOT mul_temp_19(23) & NOT mul_temp_19(23) & NOT mul_temp_19(23) & NOT mul_temp_19(23) & NOT mul_temp_19(23) & NOT mul_temp_19(23) & NOT mul_temp_19(23) & NOT mul_temp_19(23) & NOT mul_temp_19(23) & NOT mul_temp_19(23) & NOT mul_temp_19(23) & NOT mul_temp_19(23))), 23), 24);

  mul_temp_20 <= data_pipeline(3) * mu_err;
  mu_err_data_prod(3) <= resize(shift_right(mul_temp_20(46 DOWNTO 0) + ( "0" & (mul_temp_20(23) & NOT mul_temp_20(23) & NOT mul_temp_20(23) & NOT mul_temp_20(23) & NOT mul_temp_20(23) & NOT mul_temp_20(23) & NOT mul_temp_20(23) & NOT mul_temp_20(23) & NOT mul_temp_20(23) & NOT mul_temp_20(23) & NOT mul_temp_20(23) & NOT mul_temp_20(23) & NOT mul_temp_20(23) & NOT mul_temp_20(23) & NOT mul_temp_20(23) & NOT mul_temp_20(23) & NOT mul_temp_20(23) & NOT mul_temp_20(23) & NOT mul_temp_20(23) & NOT mul_temp_20(23) & NOT mul_temp_20(23) & NOT mul_temp_20(23) & NOT mul_temp_20(23))), 23), 24);

  mul_temp_21 <= data_pipeline(4) * mu_err;
  mu_err_data_prod(4) <= resize(shift_right(mul_temp_21(46 DOWNTO 0) + ( "0" & (mul_temp_21(23) & NOT mul_temp_21(23) & NOT mul_temp_21(23) & NOT mul_temp_21(23) & NOT mul_temp_21(23) & NOT mul_temp_21(23) & NOT mul_temp_21(23) & NOT mul_temp_21(23) & NOT mul_temp_21(23) & NOT mul_temp_21(23) & NOT mul_temp_21(23) & NOT mul_temp_21(23) & NOT mul_temp_21(23) & NOT mul_temp_21(23) & NOT mul_temp_21(23) & NOT mul_temp_21(23) & NOT mul_temp_21(23) & NOT mul_temp_21(23) & NOT mul_temp_21(23) & NOT mul_temp_21(23) & NOT mul_temp_21(23) & NOT mul_temp_21(23) & NOT mul_temp_21(23))), 23), 24);

  mul_temp_22 <= data_pipeline(5) * mu_err;
  mu_err_data_prod(5) <= resize(shift_right(mul_temp_22(46 DOWNTO 0) + ( "0" & (mul_temp_22(23) & NOT mul_temp_22(23) & NOT mul_temp_22(23) & NOT mul_temp_22(23) & NOT mul_temp_22(23) & NOT mul_temp_22(23) & NOT mul_temp_22(23) & NOT mul_temp_22(23) & NOT mul_temp_22(23) & NOT mul_temp_22(23) & NOT mul_temp_22(23) & NOT mul_temp_22(23) & NOT mul_temp_22(23) & NOT mul_temp_22(23) & NOT mul_temp_22(23) & NOT mul_temp_22(23) & NOT mul_temp_22(23) & NOT mul_temp_22(23) & NOT mul_temp_22(23) & NOT mul_temp_22(23) & NOT mul_temp_22(23) & NOT mul_temp_22(23) & NOT mul_temp_22(23))), 23), 24);

  mul_temp_23 <= data_pipeline(6) * mu_err;
  mu_err_data_prod(6) <= resize(shift_right(mul_temp_23(46 DOWNTO 0) + ( "0" & (mul_temp_23(23) & NOT mul_temp_23(23) & NOT mul_temp_23(23) & NOT mul_temp_23(23) & NOT mul_temp_23(23) & NOT mul_temp_23(23) & NOT mul_temp_23(23) & NOT mul_temp_23(23) & NOT mul_temp_23(23) & NOT mul_temp_23(23) & NOT mul_temp_23(23) & NOT mul_temp_23(23) & NOT mul_temp_23(23) & NOT mul_temp_23(23) & NOT mul_temp_23(23) & NOT mul_temp_23(23) & NOT mul_temp_23(23) & NOT mul_temp_23(23) & NOT mul_temp_23(23) & NOT mul_temp_23(23) & NOT mul_temp_23(23) & NOT mul_temp_23(23) & NOT mul_temp_23(23))), 23), 24);

  mul_temp_24 <= data_pipeline(7) * mu_err;
  mu_err_data_prod(7) <= resize(shift_right(mul_temp_24(46 DOWNTO 0) + ( "0" & (mul_temp_24(23) & NOT mul_temp_24(23) & NOT mul_temp_24(23) & NOT mul_temp_24(23) & NOT mul_temp_24(23) & NOT mul_temp_24(23) & NOT mul_temp_24(23) & NOT mul_temp_24(23) & NOT mul_temp_24(23) & NOT mul_temp_24(23) & NOT mul_temp_24(23) & NOT mul_temp_24(23) & NOT mul_temp_24(23) & NOT mul_temp_24(23) & NOT mul_temp_24(23) & NOT mul_temp_24(23) & NOT mul_temp_24(23) & NOT mul_temp_24(23) & NOT mul_temp_24(23) & NOT mul_temp_24(23) & NOT mul_temp_24(23) & NOT mul_temp_24(23) & NOT mul_temp_24(23))), 23), 24);

  mul_temp_25 <= data_pipeline(8) * mu_err;
  mu_err_data_prod(8) <= resize(shift_right(mul_temp_25(46 DOWNTO 0) + ( "0" & (mul_temp_25(23) & NOT mul_temp_25(23) & NOT mul_temp_25(23) & NOT mul_temp_25(23) & NOT mul_temp_25(23) & NOT mul_temp_25(23) & NOT mul_temp_25(23) & NOT mul_temp_25(23) & NOT mul_temp_25(23) & NOT mul_temp_25(23) & NOT mul_temp_25(23) & NOT mul_temp_25(23) & NOT mul_temp_25(23) & NOT mul_temp_25(23) & NOT mul_temp_25(23) & NOT mul_temp_25(23) & NOT mul_temp_25(23) & NOT mul_temp_25(23) & NOT mul_temp_25(23) & NOT mul_temp_25(23) & NOT mul_temp_25(23) & NOT mul_temp_25(23) & NOT mul_temp_25(23))), 23), 24);

  mul_temp_26 <= data_pipeline(9) * mu_err;
  mu_err_data_prod(9) <= resize(shift_right(mul_temp_26(46 DOWNTO 0) + ( "0" & (mul_temp_26(23) & NOT mul_temp_26(23) & NOT mul_temp_26(23) & NOT mul_temp_26(23) & NOT mul_temp_26(23) & NOT mul_temp_26(23) & NOT mul_temp_26(23) & NOT mul_temp_26(23) & NOT mul_temp_26(23) & NOT mul_temp_26(23) & NOT mul_temp_26(23) & NOT mul_temp_26(23) & NOT mul_temp_26(23) & NOT mul_temp_26(23) & NOT mul_temp_26(23) & NOT mul_temp_26(23) & NOT mul_temp_26(23) & NOT mul_temp_26(23) & NOT mul_temp_26(23) & NOT mul_temp_26(23) & NOT mul_temp_26(23) & NOT mul_temp_26(23) & NOT mul_temp_26(23))), 23), 24);

  mul_temp_27 <= data_pipeline(10) * mu_err;
  mu_err_data_prod(10) <= resize(shift_right(mul_temp_27(46 DOWNTO 0) + ( "0" & (mul_temp_27(23) & NOT mul_temp_27(23) & NOT mul_temp_27(23) & NOT mul_temp_27(23) & NOT mul_temp_27(23) & NOT mul_temp_27(23) & NOT mul_temp_27(23) & NOT mul_temp_27(23) & NOT mul_temp_27(23) & NOT mul_temp_27(23) & NOT mul_temp_27(23) & NOT mul_temp_27(23) & NOT mul_temp_27(23) & NOT mul_temp_27(23) & NOT mul_temp_27(23) & NOT mul_temp_27(23) & NOT mul_temp_27(23) & NOT mul_temp_27(23) & NOT mul_temp_27(23) & NOT mul_temp_27(23) & NOT mul_temp_27(23) & NOT mul_temp_27(23) & NOT mul_temp_27(23))), 23), 24);

  mul_temp_28 <= data_pipeline(11) * mu_err;
  mu_err_data_prod(11) <= resize(shift_right(mul_temp_28(46 DOWNTO 0) + ( "0" & (mul_temp_28(23) & NOT mul_temp_28(23) & NOT mul_temp_28(23) & NOT mul_temp_28(23) & NOT mul_temp_28(23) & NOT mul_temp_28(23) & NOT mul_temp_28(23) & NOT mul_temp_28(23) & NOT mul_temp_28(23) & NOT mul_temp_28(23) & NOT mul_temp_28(23) & NOT mul_temp_28(23) & NOT mul_temp_28(23) & NOT mul_temp_28(23) & NOT mul_temp_28(23) & NOT mul_temp_28(23) & NOT mul_temp_28(23) & NOT mul_temp_28(23) & NOT mul_temp_28(23) & NOT mul_temp_28(23) & NOT mul_temp_28(23) & NOT mul_temp_28(23) & NOT mul_temp_28(23))), 23), 24);

  mul_temp_29 <= data_pipeline(12) * mu_err;
  mu_err_data_prod(12) <= resize(shift_right(mul_temp_29(46 DOWNTO 0) + ( "0" & (mul_temp_29(23) & NOT mul_temp_29(23) & NOT mul_temp_29(23) & NOT mul_temp_29(23) & NOT mul_temp_29(23) & NOT mul_temp_29(23) & NOT mul_temp_29(23) & NOT mul_temp_29(23) & NOT mul_temp_29(23) & NOT mul_temp_29(23) & NOT mul_temp_29(23) & NOT mul_temp_29(23) & NOT mul_temp_29(23) & NOT mul_temp_29(23) & NOT mul_temp_29(23) & NOT mul_temp_29(23) & NOT mul_temp_29(23) & NOT mul_temp_29(23) & NOT mul_temp_29(23) & NOT mul_temp_29(23) & NOT mul_temp_29(23) & NOT mul_temp_29(23) & NOT mul_temp_29(23))), 23), 24);

  mul_temp_30 <= data_pipeline(13) * mu_err;
  mu_err_data_prod(13) <= resize(shift_right(mul_temp_30(46 DOWNTO 0) + ( "0" & (mul_temp_30(23) & NOT mul_temp_30(23) & NOT mul_temp_30(23) & NOT mul_temp_30(23) & NOT mul_temp_30(23) & NOT mul_temp_30(23) & NOT mul_temp_30(23) & NOT mul_temp_30(23) & NOT mul_temp_30(23) & NOT mul_temp_30(23) & NOT mul_temp_30(23) & NOT mul_temp_30(23) & NOT mul_temp_30(23) & NOT mul_temp_30(23) & NOT mul_temp_30(23) & NOT mul_temp_30(23) & NOT mul_temp_30(23) & NOT mul_temp_30(23) & NOT mul_temp_30(23) & NOT mul_temp_30(23) & NOT mul_temp_30(23) & NOT mul_temp_30(23) & NOT mul_temp_30(23))), 23), 24);

  mul_temp_31 <= data_pipeline(14) * mu_err;
  mu_err_data_prod(14) <= resize(shift_right(mul_temp_31(46 DOWNTO 0) + ( "0" & (mul_temp_31(23) & NOT mul_temp_31(23) & NOT mul_temp_31(23) & NOT mul_temp_31(23) & NOT mul_temp_31(23) & NOT mul_temp_31(23) & NOT mul_temp_31(23) & NOT mul_temp_31(23) & NOT mul_temp_31(23) & NOT mul_temp_31(23) & NOT mul_temp_31(23) & NOT mul_temp_31(23) & NOT mul_temp_31(23) & NOT mul_temp_31(23) & NOT mul_temp_31(23) & NOT mul_temp_31(23) & NOT mul_temp_31(23) & NOT mul_temp_31(23) & NOT mul_temp_31(23) & NOT mul_temp_31(23) & NOT mul_temp_31(23) & NOT mul_temp_31(23) & NOT mul_temp_31(23))), 23), 24);

  mul_temp_32 <= data_pipeline(15) * mu_err;
  mu_err_data_prod(15) <= resize(shift_right(mul_temp_32(46 DOWNTO 0) + ( "0" & (mul_temp_32(23) & NOT mul_temp_32(23) & NOT mul_temp_32(23) & NOT mul_temp_32(23) & NOT mul_temp_32(23) & NOT mul_temp_32(23) & NOT mul_temp_32(23) & NOT mul_temp_32(23) & NOT mul_temp_32(23) & NOT mul_temp_32(23) & NOT mul_temp_32(23) & NOT mul_temp_32(23) & NOT mul_temp_32(23) & NOT mul_temp_32(23) & NOT mul_temp_32(23) & NOT mul_temp_32(23) & NOT mul_temp_32(23) & NOT mul_temp_32(23) & NOT mul_temp_32(23) & NOT mul_temp_32(23) & NOT mul_temp_32(23) & NOT mul_temp_32(23) & NOT mul_temp_32(23))), 23), 24);

-- * LMS_Filter Weight Accumulator

  add_cast_30 <= weight(0);
  add_cast_31 <= mu_err_data_prod(0);
  add_temp_15 <= resize(add_cast_30, 25) + resize(add_cast_31, 25);
  weight_adder_output(0) <= add_temp_15(23 DOWNTO 0);

  add_cast_32 <= weight(1);
  add_cast_33 <= mu_err_data_prod(1);
  add_temp_16 <= resize(add_cast_32, 25) + resize(add_cast_33, 25);
  weight_adder_output(1) <= add_temp_16(23 DOWNTO 0);

  add_cast_34 <= weight(2);
  add_cast_35 <= mu_err_data_prod(2);
  add_temp_17 <= resize(add_cast_34, 25) + resize(add_cast_35, 25);
  weight_adder_output(2) <= add_temp_17(23 DOWNTO 0);

  add_cast_36 <= weight(3);
  add_cast_37 <= mu_err_data_prod(3);
  add_temp_18 <= resize(add_cast_36, 25) + resize(add_cast_37, 25);
  weight_adder_output(3) <= add_temp_18(23 DOWNTO 0);

  add_cast_38 <= weight(4);
  add_cast_39 <= mu_err_data_prod(4);
  add_temp_19 <= resize(add_cast_38, 25) + resize(add_cast_39, 25);
  weight_adder_output(4) <= add_temp_19(23 DOWNTO 0);

  add_cast_40 <= weight(5);
  add_cast_41 <= mu_err_data_prod(5);
  add_temp_20 <= resize(add_cast_40, 25) + resize(add_cast_41, 25);
  weight_adder_output(5) <= add_temp_20(23 DOWNTO 0);

  add_cast_42 <= weight(6);
  add_cast_43 <= mu_err_data_prod(6);
  add_temp_21 <= resize(add_cast_42, 25) + resize(add_cast_43, 25);
  weight_adder_output(6) <= add_temp_21(23 DOWNTO 0);

  add_cast_44 <= weight(7);
  add_cast_45 <= mu_err_data_prod(7);
  add_temp_22 <= resize(add_cast_44, 25) + resize(add_cast_45, 25);
  weight_adder_output(7) <= add_temp_22(23 DOWNTO 0);

  add_cast_46 <= weight(8);
  add_cast_47 <= mu_err_data_prod(8);
  add_temp_23 <= resize(add_cast_46, 25) + resize(add_cast_47, 25);
  weight_adder_output(8) <= add_temp_23(23 DOWNTO 0);

  add_cast_48 <= weight(9);
  add_cast_49 <= mu_err_data_prod(9);
  add_temp_24 <= resize(add_cast_48, 25) + resize(add_cast_49, 25);
  weight_adder_output(9) <= add_temp_24(23 DOWNTO 0);

  add_cast_50 <= weight(10);
  add_cast_51 <= mu_err_data_prod(10);
  add_temp_25 <= resize(add_cast_50, 25) + resize(add_cast_51, 25);
  weight_adder_output(10) <= add_temp_25(23 DOWNTO 0);

  add_cast_52 <= weight(11);
  add_cast_53 <= mu_err_data_prod(11);
  add_temp_26 <= resize(add_cast_52, 25) + resize(add_cast_53, 25);
  weight_adder_output(11) <= add_temp_26(23 DOWNTO 0);

  add_cast_54 <= weight(12);
  add_cast_55 <= mu_err_data_prod(12);
  add_temp_27 <= resize(add_cast_54, 25) + resize(add_cast_55, 25);
  weight_adder_output(12) <= add_temp_27(23 DOWNTO 0);

  add_cast_56 <= weight(13);
  add_cast_57 <= mu_err_data_prod(13);
  add_temp_28 <= resize(add_cast_56, 25) + resize(add_cast_57, 25);
  weight_adder_output(13) <= add_temp_28(23 DOWNTO 0);

  add_cast_58 <= weight(14);
  add_cast_59 <= mu_err_data_prod(14);
  add_temp_29 <= resize(add_cast_58, 25) + resize(add_cast_59, 25);
  weight_adder_output(14) <= add_temp_29(23 DOWNTO 0);

  add_cast_60 <= weight(15);
  add_cast_61 <= mu_err_data_prod(15);
  add_temp_30 <= resize(add_cast_60, 25) + resize(add_cast_61, 25);
  weight_adder_output(15) <= add_temp_30(23 DOWNTO 0);

  LMS_Filter_acc_temp_process2 : PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF reset = '0' THEN
        weight <= (OTHERS => (OTHERS => '0'));
      ELSIF enb = '1' THEN
        weight(0 TO 15) <= weight_adder_output(0 TO 15);
      END IF;
    END IF;
  END PROCESS LMS_Filter_acc_temp_process2;


  e_k <= std_logic_vector(LMS_Filter_out2);

  o_k <= std_logic_vector(LMS_Filter_out1);

  ce_out <= clk_enable;

END rtl;

